### ISSUE TITLE
`Unhandled error: TypeError: Cannot read properties of undefined (reading 'html_url')`

### ISSUE THREAD

**Issue by garysassano** [DevSecTop/TF-via-PR#237]
#### Describe the bug

GitHub Actions fails when the job name includes spaces or other unallowed characters.
Can be fixed by sanitizing the job name.

#### Screenshots

![image](https://github.com/DevSecTop/TF-via-PR/assets/10464497/e2751dbd-ae35-4373-a539-82c2a1758d1f)

**Comment by RDhar** [comment]
One of the complicating factors here is that the job name is used as a unique identifer, while GitHub Actions currently does not expose this job property consistently, as [raised here](https://github.com/orgs/community/discussions/129314).

That being said, I'll see to partial matching so that both matrix and regular jobs are served reliably. If a [custom name](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idname) is supplied and there's no way to reconcile it, then fallback on the first job of a workflow so that this step never fails.

**Comment by RDhar** [comment]
Shipped in [v11.0.0](https://github.com/DevSecTop/TF-via-PR/releases/tag/v11.0.0) :rocket:
