### ISSUE TITLE
GitHub secrets exposed in PR comments

### ISSUE THREAD

**Issue by garysassano** [DevSecTop/TF-via-PR#278]
#### Describe the bug

There is a critical issue that needs immediate attention. When a GitHub secret is passed in via the `arg_env` input parameter, it gets automatically redacted in Job Summaries. However, this redaction does not occur in the PR comments posted by the `tf-via-pr` action.

#### Screenshots

![alt text](https://github.com/user-attachments/assets/4acd01c0-2f40-4da7-a090-0ca7db9b6144)

![alt text](https://github.com/user-attachments/assets/0114fb48-ad1e-4983-95bf-bcf18a841efb)

**Comment by RDhar** [comment]
Given that the workflow simply returns its command input to the PR comment, I'm inclined to label this as expected behaviour: especially given the context that sentive input variables (e.g., credentials/tokens) should be passed in as `TF_VAR_<name>` prefixed environment variables, as [documented here](https://developer.hashicorp.com/terraform/tutorials/configuration-language/sensitive-variables).

With that said, I do see value in [optionally hiding user-configured input arguments](https://github.com/DevSecTop/TF-via-PR/pull/279) from the PR comment, if not to hide secrets, but limit it to relevant information only. For example, hiding the `-lock` argument since it doesn't add a whole lot of value in each PR comment.
